# Generated by Django 5.0.7 on 2024-07-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='picture',
            field=models.ImageField(default='default_group_pic/default_group_pic.png', upload_to='group_pictures/'),
        ),
    ]
